version: "3"
services:
  node:
    build:
      context: .
      dockerfile: infrastructure/docker/dockerfile-node
    volumes:
      - ./:/code
    working_dir: /code
    command: npm run bootstrap
    environment:
      HOST: 0.0.0.0
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_AUTHORIZATION_URI: ${KEYCLOAK_AUTHORIZATION_URI}
      KEYCLOAK_USERINFO_URI: ${KEYCLOAK_USERINFO_URI}
      KEYCLOAK_LOGOUT_URI: ${KEYCLOAK_ACCOUNT_URI}
      MONOREPO_IMPORT: ${MONOREPO_IMPORT}
    ports:
      - "${SERVER_PORT:-3000}:3000"
