version: '3'
services:
  node:
    build:
      context: .
      dockerfile: infrastructure/docker/dockerfile-node
    volumes:
      - ./:/code
    working_dir: /code
    command: npm run storybook
    environment:
      HOST: 0.0.0.0
    ports:
      - '${SERVER_PORT:-8000}:8000'
