name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          
      - name: install
        run: |
            npm ci
            npm run bootstrap
            
      - name: lint
        run: npm run lint
	working-directory: databrowser
        
      - name: build
        run: npm run build
	working-directory: databrowser

