name: CI/CD

on: push

env:
  AWS_REGION : "eu-west-1"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
        working-directory: databrowser
      - run: npm run lint
        working-directory: databrowser
      - run: npm run test
        working-directory: databrowser

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/development'
    needs: test
    env:
      BUCKET_NAME : "it.bz.opendatahub.databrowser-test"
      VITE_APP_KEYCLOAK_URL: "https://auth.opendatahub.testingmachine.eu/auth"
      VITE_APP_KEYCLOAK_REALM: "noi"
      VITE_APP_KEYCLOAK_CLIENT_ID: "it.bz.opendatahub.databrowser"
      VITE_APP_KEYCLOAK_REDIRECT_URI: "https://databrowser.opendatahub.testingmachine.eu/silent-check-sso.html"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
        working-directory: databrowser
      - run: npm run build
        working-directory: databrowser
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 sync --delete ./dist s3://${{ env.BUCKET_NAME }}
        working-directory: databrowser

  deploy-prod:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    env:
      BUCKET_NAME : "it.bz.opendatahub.databrowser-prod"
      VITE_APP_KEYCLOAK_URL: "https://auth.opendatahub.bz.it/auth"
      VITE_APP_KEYCLOAK_REALM: "noi"
      VITE_APP_KEYCLOAK_CLIENT_ID: "it.bz.opendatahub.databrowser"
      VITE_APP_KEYCLOAK_REDIRECT_URI: "https://databrowser.opendatahub.bz.it/silent-check-sso.html"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
        working-directory: databrowser
      - run: npm run build
        working-directory: databrowser
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 sync --delete ./dist s3://${{ env.BUCKET_NAME }}
        working-directory: databrowser
